// Bark 2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

var pupEuler2=()=>{
  var i;var sum = 0;var fib = [];
  fib[0] = 0;fib[1] = 1;
  for(i=2;fib[i-2]+fib[i-1]<=4000000;i++){
    fib[i] = fib[i-2] + fib[i-1];
    if(!(fib[i]%2)){sum+=fib[i];}
  }
  return sum;
}

pupEuler2();

module.exports = pupEuler2;
