# Bark 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def pup_euler2
a = [1,2]

#Puponacci Series
a << a[-2] + a[-1] while a[-2] + a[-1] < 4_000_000
# Sum of puponacci numbers
a.delete_if(&:odd?).inject(:+)
end

unless ENV['RACK_ENV'] == 'test'
  require_relative "vars";s = Vars::Sentence.new
  puts s.solution(pup_euler2)
end
