require_relative "../ruby/vars"

def fmt(txt)
  txt.gsub(/(.{1,#{55}})( +|$\n?)|(.{1,#{55}})/,
    "\\1\\3\n")
end


def questions
  {
    1 => fmt("If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000."),
    2 => fmt("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."),
    3 => fmt("The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 60085147514"),
    4 => fmt("A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the product of two 3-digit numbers."),
    5 => fmt("2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder. What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"),
    6 => fmt("The sum of the squares of the first ten natural numbers is, 12 + 22 + ... + 102 = 385 ; The square of the sum of the first ten natural numbers is, (1 + 2 + ... + 10)2 = 552 = 3025 ; Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640. Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."),
    7 => fmt("By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 10 001st prime number?"),
    8 => fmt("The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832. ") + "\n#{Vars::P8_NUM}\n" + fmt("\nFind the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?"),
    9 => fmt("A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a**2 + b**2 = c**2\n\nFor example, 3**2 + 4**2 = 9 + 16 = 25 = 5**2.\n\nThere exists exactly one Pythagorean triplet for which a + b + c = 1000. Find the product abc."),
    10 => fmt("The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17. Find the sum of all the primes below two million."),
    13 => fmt("Work out the first ten digits of the sum of the following one-hundred 50-digit numbers.") + "\n\t#{Vars::P13_NUM}",
    56 => fmt("A googol (10100) is a massive number: one followed by one-hundred zeros; 100100 is almost unimaginably large: one followed by two-hundred zeros. Despite their size, the sum of the digits in each number is only 1.\nConsidering natural numbers of the form, ab, where a, b < 100, what is the maximum digital sum?")
  }
end
